// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sMLqy7v23gdsoz-yAKPChp-tXMiLfs8',
    appId: '1:596755320834:web:8114646a67c1a40accd71b',
    messagingSenderId: '596755320834',
    projectId: 'afterglow-agenda',
    authDomain: 'afterglow-agenda.firebaseapp.com',
    storageBucket: 'afterglow-agenda.firebasestorage.app',
    measurementId: 'G-CR5N93T48P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNGklqtMpb-CB-J8TEDIODFU3gehkL7i8',
    appId: '1:596755320834:android:e2e38da2edb3d0e5ccd71b',
    messagingSenderId: '596755320834',
    projectId: 'afterglow-agenda',
    storageBucket: 'afterglow-agenda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3WrbH34mRXr4eLSPl_qiJlU-A2inWt_Q',
    appId: '1:596755320834:ios:231fe884eb05ed1cccd71b',
    messagingSenderId: '596755320834',
    projectId: 'afterglow-agenda',
    storageBucket: 'afterglow-agenda.firebasestorage.app',
    iosBundleId: 'com.example.afterglowAgenda',
  );
}
